config/routes.rb
Rails.application.routes.draw do
  resources :properties
    root 'properties#index'
    resources :stations
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
   has_many :stations
   validates :property, presence: true
   validates :rent, presence: true
   validates :address, presence: true
   validates :age, presence: true
   #validates :remarks, presence: true
   accepts_nested_attributes_for :stations, allow_destroy: true,reject_if: :all_blank

   def check
    if minutes_on_foot.present? && minutes_on_foot1.present?
      if minutes_on_foot <= minutes_on_foot1
        errors.add(:minutes_on_foot, 'Station one is further than station two')
      end
    end
  end
end

app/models/stations.rb
class Station < ApplicationRecord
  belongs_to :property, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show,:edit,:update,:destroy]

    def index
      @properties = Property.all
    end

    def new
      @property = Property.new
      #2.times { @property.stations.build }
     end

     def create
       @property = Property.new(property_params)

        respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end
    def show
    end

    def edit
  #  1.times { @property.stations.build }
    end

    def update
      respond_to do |format|
        if @property.update(property_params)
          format.html { redirect_to @property, notice: 'Property was successfully updated.' }
          format.json { render :show, status: :ok, location: @property }
        else
          format.html { render :edit }
          format.json { render json: @property.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @property.destroy
      respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
    end
  end

    private
        def set_property
          @property = Property.find(params[:id])
        end
        def property_params
          params.require(:property).permit(:property, :rent, :address, :age, :remarks, :id, :station_name, :line_name, :minutes_on_foot,)

    end
  end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]


    def index
      @stations = Station.all
    end


    def show
    end

    def new
      @station = Station.new
    end

    def edit
    end

    def create
      @station = Station.new(station_params)

      respond_to do |format|
        if @station.save
          format.html { redirect_to @station, notice: 'Station was successfully created.' }
          format.json { render :show, status: :created, location: @station }
        else
          format.html { render :new }
          format.json { render json: @station.errors, status: :unprocessable_entity }
        end
      end
    end


    def update
      respond_to do |format|
        if @station.update(station_params)
          format.html { redirect_to @station, notice: 'Station was successfully updated.' }
          format.json { render :show, status: :ok, location: @station }
        else
          format.html { render :edit }
          format.json { render json: @station.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @station.destroy
      respond_to do |format|
        format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      def set_station
        @station = Station.find(params[:id])
      end

      def station_params
        params.require(:station).permit(:line_name, :station_name, :minutes_on_foot, :property_id)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mofmof</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: @property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :property %>
    <br>
    <%= form.text_field :property %>
  </div>

  <div class="field">
    <%= form.label :rent %>
    <br>
    <%= form.number_field :rent %>JPY
  </div>

  <div class="field">
    <%= form.label :address %>
    <br>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <br>
    <%= form.number_field :age %>Years/Years old
  </div>

  <div class="border_new">
    <%= form.label :remarks %>
    <br>
    <%= form.text_area :remarks %>
  </div>

  <% @tag_number = 1 %>
  <%= form.fields_for :station do |station| %>
    <h2>Nearest station<%= @tag_number %></h2>
    <% @tag_number += 1 %>
    <div class="line_name">
      <%= station.label :station_name %><br>
      <%= station.text_field :line_name %>
    </div>
    <div class="station_name">
      <%= station.label :line_name %><br>
      <%= station.text_field :station_name %>
    </div>
    <div class="minutes_on_foot">
      <%= station.label :minutes_on_foot %><br>
      <%= station.text_field :minutes_on_foot %>min/mins<br>
    </div>
  <% end %>
  <br>
  <%= form.submit 'submit' %>
<% end %>

app/views/properties/edit.html.erb
<h1>property editing</h1>

<%= render 'form', property: @property %>

<%= link_to 'show', @property %>

<%= link_to 'back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        Properties
      </div>
      <div class="card-body">


<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>rent</th>
      <th>address</th>
      <th> age</th>
      <th>remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.property %></td>
        <td><%= property.rent %></td>
        <td><%= property.address %></td>
        <td><%= property.age %></td>
        <td><%= property.remarks %></td>
        <td><%= link_to 'Show', property , class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_property_path(property) , class: "btn btn-primary"  %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn "%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="actions">
  <%= link_to 'New Property', new_property_path , class: "btn btn-primary"  %>
</div>

  </div>
    </div>
      </div>
        </div>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form',property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @property.property %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @property.rent %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>age:</strong>
  <%= @property.age %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @property.remarks %>
</p>
<hr>
<% @property.stations.each do |poor| %>
  <h2><b>Nearest station </b></h2>
  <p>
    <strong>Name line:</strong>
    <%= poor.line_name %>
  </p>

  <p>
    <strong>Station name:</strong>
    <%= poor.station_name %>
  </p>

  <p>
    <strong>How many minutes walks:</strong>
    <%= poor.minutes_on_foot %>
    </p>
<% end %>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/stations/ edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/ index.html.erb
<p><%= notice %></p>

<h1>stations</h1>

<table>
  <thead>
    <tr>
      <th>line name</th>
      <th>Station name</th>
      <th>minutes on foot</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |station| %>
      <tr>
        <td><%= station.line_name %></td>
        <td><%= station.station_name %>円</td>
        <td><%= station.minutes_on_foot %></td>
        <td><%= station.property %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'you sure？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New station', new_station_path %>

app/views/stations/ new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/ show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>line name:</strong>
  <%= @station.line_name %>
</p>

<p>
  <strong>Station name:</strong>
  <%= @station.station_name %>
</p>

<p>
  <strong>Minutes walk:</strong>
  <%= @station.minutes_on_foot %>
</p>

<p>
  <strong>Property:</strong>
  <%= @station.property %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>

app/views/stations/_form.html.erb
<%= form_for(station) do |f| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :line_name %>
    <%= f.text_field :line_name %>
  </div>

  <div class="field">
    <%= f.label :station_name %>
    <%= f.text_field :station_name %>
  </div>

  <div class="field">
    <%= f.label :minutes_on_foot %>
    <%= f.number_field :minutes_on_foot %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>